redis:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    env: staging
    tier: backend
    app: worker
  tty: true
  log_opt: {}
  image: redis
  stdin_open: true
voting-app:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    env: staging
    tier: frontend
    app: web
  tty: true
  log_opt: {}
  image: janeczku/voting-app
  environment:
    - STATSD_HOST=datadog-agent.datadog
  links:
  - 'voting-app:'
  stdin_open: true
External-LB:
  ports:
  - 5000:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - voting-app:voting-app
  stdin_open: true
result-app:
  ports:
  - 5001:80/tcp
  log_driver: ''
  labels:
    env: staging
    tier: frontend
    app: web
  tty: true
  log_opt: {}
  image: cloudnautique/result-app
  links:
  - Postrges:db
  stdin_open: true
worker:
  log_driver: ''
  labels:
    env: staging
    tier: backend
    app: worker
  tty: true
  log_opt: {}
  image: cloudnautique/worker
  links:
  - redis:redis
  - Postrges:db
  stdin_open: true
Postrges:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    env: staging
    tier: backend
    app: database
  tty: true
  log_opt: {}
  image: postgres:9.4
  volumes:
  - db-data:/var/lib/postgresql/data
  stdin_open: true
